### ISSUE TITLE
Option to use interactive objects without auto updating render

### ISSUE THREAD

**Issue by daevid66** [grischaerbe/threlte#53]
Just started trying out Threlte and like it a lot :)

I wonder what the reason is for making the scene auto-render if there is an interactive object in the scene? I tested to remove lines 47-48 in frameloop.js and using the orbit-control and clicking on objects works just fine. I have not tested hover states etc yet, though.

I really like that the default in threlte is to not render if nothing has changed in the scene, so if auto-update is needed for some but not all interactivity it would be great to be able to have a setting for this.

Cheers,

David

**Comment by grischaerbe** [comment]
Hi @daevid66,

The frame loop is running continuously because the events `pointerenter` and `pointerleave` cannot be derived from their DOM counterparts. They would fire if you enter or leave the canvas – not a particular mesh that is drawn to it. This is why these events need the continuous frame loop. There's also the possibility that some object moves underneath the cursor, either having the cursor enter or leave the object without the cursor actually moving, so this cannot be achieved with DOM events unfortunately. I totally get your point and it's something I worked on a lot, if you have any idea where to go with this, go ahead :)
You could of course make your own performance improvements. There's a flag in `useThrelte()`: `pointerOverCanvas`. You could use it to set certain `<Mesh>` components to `interactive={false}`.

**Comment by daevid66** [comment]
Hmm I see, I might be totally wrong here but would it not be possible to do the raycasts necessary for the pointer enter/leave events every frame (or every frame where the pointer or scene has been updated) without actually re-rendering the scene?

**Comment by grischaerbe** [comment]
three.js updates all the objects in the scene in order to raycast on them. My best guess is that these updates are applied to object matrices on `renderer.render`. You can of course set these to not auto-update and then handle everything on your own.
Feel free to give it a try – raycasting without rendering, I'm curious!

**Comment by daevid66** [comment]
If I for example move the the call to animationFrameRaycast in frameloop to always run (should be optimized to only run if a pointer has moved or scene/camera is updated), the pointer leave/enter events are still working for me.

In my head the objects transforms should always be updated since we always do a render whenever the scene or camera has moved. 

I will try to make a proof of concept PR later this week. I will probably need to add a flag, for example pointerHasMoved on the renderContext.

**Comment by grischaerbe** [comment]
Interesting. In essence there's two things to account for:
a) the user moving the pointer over an object
b) the object moving under the cursor

a) could be done by listening to the `pointermove` event on the `<canvas>`
b) is already there as transforms to an object lead to the invalidation of the frame.

Am I missing something?

**Comment by daevid66** [comment]
No, I think it should be fairly simple. But I'm not used to doing PR's for npm packages so it will take me some time to setup a test environment. I guess i could just copy the typescript files into a project to test and then copy back the changes instead of creating a forked npm package.

**Comment by grischaerbe** [comment]
Alright, looking forward. If you need help with setting up your environment, I'm active at [Discord → Svelte → #gl](https://discord.com/channels/457912077277855764/678020543286476820).
