### ISSUE TITLE
Disabling click events when dragging scene with orbit control

### ISSUE THREAD

**Issue by daevid66** [grischaerbe/threlte#54]
When dragging the scene and ending the drag above an interactive object, a click event is triggered from the object. When dragging on touch screen I don't get this behavior, and I would expect to only get the click handler if I have not initiated a drag.

In previous projects with three I have listened on movement from the orbit-control and stopped the propagation of the click events if the user has moved more than threshold values for distance or duration. I've also done the opposite, if a scene object is dragged the orbit-control is inactivated during the drag duration. Not sure how the interactivity works in threlte yet, though.

Cheers,

David

**Comment by grischaerbe** [comment]
Your described behaviour is actually in-line with regular DOM events. "Dragging" on a DOM element (that is mousedown somewhere on the element, mousemove on the element and mouseup on the element) triggers a click event. This might seem counterintuitive at first, but I wanted to adhere to regular DOM events as much as possible. See this [REPL](https://svelte.dev/repl/f97a0b143111442fbdd416b077c53cf1?version=3.47.0).

The `<Orbitcontrols>` emit certain events on user interaction, feel free to use that to build your drag interaction.
In my opinion accounting for interferences between Controls and "regular" events is something that is out of reach of this project as that is something that is totally up to the individual design of the whole experience you are trying to achieve.

**Comment by daevid66** [comment]
I do understand that if I drag on top of a button element an release on the same element, I should get a click event. But I don't think its standard that you get a click event when you are interacting/dragging an element.

I added a "click" message in this repl: https://svelte.dev/repl/adf5a97b91164c239cc1e6d0c76c2abe?version=3.14.1
It is not triggered if I drag and release one of the boxes.

Another example is google maps, and well, almost all instances I can think of where you drag objects on the screen. You almost always want to be able to differentiate between a drag and a click.

Currently the only way I can do this is to listen for drag events on the orbitcontrol to set a flag and then check this flag in every click handler bound to objects in the scene. Not a big problem but it might be easier if I could handle this globally somehow.

But I totally understand that you want/need to scope the project. You have done a lot of amazing work on this lib!

**Comment by ShaddyDC** [comment]
I recently ran into this problem as well, and it's very unintuitive behaviour to me. I can open a new issue since this one is really old, but I figured I'll put it here so you can just leave this issue closed if this is in fact something you're not looking to change.

If I've got a scene above a button like this:

![image](https://github.com/user-attachments/assets/15a6a83d-a2e3-4f54-9a03-1421764a3740)

I rotate the scene by clicking in it and dragging, and I release while I'm above the button. Then the button is triggered.
I was really surprised by this at first because I was looking at the rotating object and didn't even notice I was above the button, so it took me a bit to understand why something was happening at all.

I'd strongly prefer a different behaviour, and I don't understand why anybody would expect it to work like this, but I will respect if this is intended and you don't want to change it.
