### ISSUE TITLE
useThrelte crashes the app

### ISSUE THREAD

**Issue by takoyaro** [grischaerbe/threlte#62]
Adding `useThrelte` to the list of imports works fine but as soon as you try to [use it like the docs say](https://threlte.xyz/docs/hooks/useThrelte), the app crashes and you get this error:

> Cannot destructure property 'size' of '__vite_ssr_import_3__.useThrelte(...)' as it is undefined.

_Reproduction Environment_
https://stackblitz.com/edit/sveltejs-kit-template-default-1fxljc?file=src/routes/index.svelte

I understand `useThrelte` uses a getContext/setContext under the hood but I don't fully grasp that aspect of Svelte so unfortunately I can't fix this myself.

**Comment by grischaerbe** [comment]
The context that `useThrelte` and other hooks are relying on are provided by the `<Canvas>` component. My guess is that your app currently looks something like this:

```svelte
<script>
import { useThrelte, Canvas, PerspectiveCamera, Mesh } from 'threlte'

// This will crash
const { size } = useThrelte
$: console.log($size)
</script>

<Canvas>
  <PerspectiveCamera … />

  <Mesh … />
</Canvas>
```
As the component `<Canvas>` and the usage of `useThrelte` live in the same component, the context provided by `<Canvas>` is not available. You need to nest the components in separate files in order to make use of ``the context:

Wrapper.svelte:
```svelte
<script>
import { Canvas } from 'threlte'
import Scene from './Scene.svelte'
</script>

<Canvas>
  <Scene />
</Canvas>
```
Scene.svelte:
```svelte
<script>
import { useThrelte, PerspectiveCamera, Mesh } from 'threlte'

// We have access to the context since
// we are in a child component to <Canvas>
const { size } = useThrelte
$: console.log($size)
</script>

<PerspectiveCamera … />
<Mesh … />
```
In most projects when you reach a certain complexity this structure comes naturally. *If* you want to stay in a single component structure, there's a way too:

```svelte
<script>
import { Canvas, PerspectiveCamera, Mesh } from 'threlte'

let ctx
$: console.log(ctx)
</script>

<Canvas bind:ctx>
  <PerspectiveCamera … />

  <Mesh … />
</Canvas>
```

but I would suggest otherwise as Sveltes automatic store subscriptions won't work in this approach (no store and $store).

Hope that helps!
What I learn from this issue is that the docs need to be more clear about the usage of context-aware hooks and objects.

**Comment by takoyaro** [comment]
This is more than a satisfying answer, thank you for laying it out like this. I really appreciate it.

> What I learn from this issue is that the docs need to be more clear about the usage of context-aware hooks and objects.

I couldn't agree more. I'd be more than happy to submit PRs for the docs if they are welcome.

**Comment by grischaerbe** [comment]
Absolutely, go ahead! PRs in every direction are very much appreciated. Documentation is key and insights from people who use it based on the docs is highly valuable.

**Comment by dp1140a** [comment]
I followed the instructions above and while this works
```javascript
let ctx
$: console.log(ctx)
```
although it runs twice.  The first time it is undefined the second i get the ctx.

i cant access anything inside ctx.  so if I try 
```javascript
let ctx
$: console.log(ctx.camera)
```
barfs.

Here is my current +page.svelte component:
```html
<script>
	import {
		T,
		Canvas,
		useThrelte
	} from "@threlte/core";

	import {
		OrbitControls,
	} from "@threlte/extras";

	import{
		MeshStandardMaterial,
	} from "three"

	export let data;

	let ctx
	$: console.log(ctx)
</script>

<div>
	<Canvas bind:ctx>
		<T.PerspectiveCamera
			makeDefault
			position={[10,10,50]}
			on:create={({ ref }) => {
    ref.lookAt(0, 1, 0)
  }}>
			<OrbitControls enableDamping maxDistance=200 minDistance=10/>
		</T.PerspectiveCamera>

		<T.DirectionalLight position={[1, 10, 1]} intesity={".5"}/>
		<T.HemisphereLight color={"green"} intensity=".5"/>
		<T.Mesh
			geometry={data.stlModel}
			material={new MeshStandardMaterial({ color: '#953620' })}
		/>

	</Canvas>
</div>
```

In the end what Im trying to do is set the camera position based on the size of the object rendered.
