### ISSUE TITLE
useTexture() js file size (500Kib)

### ISSUE THREAD

**Issue by silveltman** [grischaerbe/threlte#77]
I just ran my vite build and the file size of the useTexture function really stood out:

```
vite v2.9.14 building for production...
✓ 104 modules transformed.
dist/client.17d98c6c.js              0.42 KiB / gzip: 0.32 KiB
dist/assets/e3b0c442.9e659790.css    0.04 KiB / gzip: 0.05 KiB
dist/Wrapper.214e8078.js             2.12 KiB / gzip: 1.02 KiB
dist/Wrapper.991589b8.js             1.97 KiB / gzip: 0.93 KiB
dist/client.c29c847b.js              50.32 KiB / gzip: 20.35 KiB
dist/chunks/useTexture.37f8dbe3.js   507.74 KiB / gzip: 133.75 KiB
```

Does this have something to do with the texture/image file included in this file or something? Or might it have something to do with my setup? I'm running in Astro.

_PS: is it okay to use .webp as input for useTexture?_

Thanks! :)

**Comment by grischaerbe** [comment]
Hey @silveltman,

this is probably due to three.js being hard to treeshake for bundlers. There are approaches to reducing the bundle size with more aggressive treeshaking, see [this comment](https://github.com/grischaerbe/threlte/issues/8#issuecomment-1024085864) for a ~30% reduction on average in my projects.
And yes, you can use .webp images as long as the browser supports it.
